// client-react/src/views/App/App.jsx
import React, { Component } from "react";

import "./App.scss";

import Nav from "../../components/Nav/Nav";
import Header from "../../components/App/Header/Header";

class App extends Component {
  render() {
    return (
      <div>
        <Nav />
        <Header />
      </div>
    );
  }
}

export default App;

// client-vue/src/App.vue
<template>
  <div id="app">
    <Nav />
    <router-view/>
  </div>
</template>

<script>
import Nav from '@/components/Nav.vue';

export default {
  name: 'App',
  components: { Nav },
};
</script>


<style lang="scss" scoped>
@import "~animate.css/animate.min.css";
@import "~@/assets/styles/index";
</style>
